### ISSUE TITLE
Add Fastly as new provider

### ISSUE THREAD

**Issue by stefounet** [fasterize/darkstar#2]
Some Fasterize users starts to use Fastly as a CDN, we should add it to Darkstar (see https://docs.fastly.com/api/purge)

**Comment by dax** [comment]
Hi @ssuda, we cannot hire you on upwork as we have the following message: " This freelancer is not available for job invitations."
Is there something you can do on your side so that we can hire you?

**Comment by ssuda** [comment]
Hi David, Thanks so much for your reply.
Upwork profile is recently created. It is not approved.
I am available for freelancing outside of upwork. Please let me know, how to proceed.
Here is my linkedin profile for your reference.
Sambasiva Suda - Founder - PubMesh Inc | LinkedIn  
|  
|   
|   
|   |    |

   |

  |
|  
|   |  
Sambasiva Suda - Founder - PubMesh Inc | LinkedIn
 
View Sambasiva Suda’s profile on LinkedIn, the world's largest professional community. Sambasiva has 6 jobs jobs listed on their profile. See the complete profile on LinkedIn and discover Sambasiva’s connections and jobs at similar companies.
  |   |

  |

  |

  

I also contributed to nodejs core.
Thanks and regardsSambasiva

Sent from Yahoo Mail on Android 
 
  On Fri, 20 Apr 2018 at 3:02 pm, David Rousselie<notifications@github.com> wrote:   
Hi @ssuda, we cannot hire you on upwork as we have the following message: " This freelancer is not available for job invitations."
Is there something you can do on your side so that we can hire you?

**Comment by ssuda** [comment]
Hi David, you can invite me in upwork. Please take a look at this https://support.upwork.com/hc/en-us/articles/211063588

**Comment by dax** [comment]
@ssuda I require your email address so that I can invite you on upwork.

**Comment by ssuda** [comment]
username: ssamba
email: samba@pubmesh.com

**Comment by ssuda** [comment]
@dax please invite me in upwork
